[package]
name = "ptdecoder"
version = "0.1.0"
authors = ["Sirui Mu <msrlancern@126.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
libipt = "0.1.4"
